import { GLTF } from 'three-stdlib'
import type { Mesh, MeshStandardMaterial, MeshPhysicalMaterial } from 'three'

interface GLTFResult extends GLTF {
   nodes: {
      Walls: Mesh
      WallBorder: Mesh
      Chair: Mesh
      Circle: Mesh
      Circle001: Mesh
      Cube001: Mesh
      Cylinder005: Mesh
      Cylinder006: Mesh
      Cylinder007: Mesh
      Cylinder008: Mesh
      Cylinder009: Mesh
      Cylinder010: Mesh
      Plane: Mesh
      Plane001: Mesh
      Cylinder012_1: Mesh
      Cylinder012_2: Mesh
      Lamp: Mesh
      Flower: Mesh
      Cylinder011: Mesh
      Plane003: Mesh
      Plane004: Mesh
      Plane005: Mesh
      Plane006: Mesh
      Plane008: Mesh
      Background: Mesh
      Background001: Mesh
      CertFrameReact: Mesh
      React: Mesh
      CertFrameFrontend: Mesh
      Frontend: Mesh
      CertFrameLLM: Mesh
      LLM: Mesh
      ThomasText: Mesh
      Flooring2: Mesh
      Cylinder: Mesh
      Cylinder001: Mesh
      Cylinder002: Mesh
      WindowShade: Mesh
      Cylinder003: Mesh
      Cylinder004: Mesh
      WindowFrame: Mesh
      Window: Mesh
      WindowGlass: Mesh
      Matress: Mesh
      Pillow01: Mesh
      Pillow02: Mesh
      Sheet: Mesh
      BedFrame: Mesh
      DeskTable: Mesh
      DeskBottom: Mesh
      DeskFrame: Mesh
      DeskLeg: Mesh
      DeskLegs: Mesh
      Circle002: Mesh
      Cube027: Mesh
      Cube027_1: Mesh
      Cube009: Mesh
      Mouse: Mesh
      Cylinder012: Mesh
      Mouse001: Mesh
      Cube: Mesh
      Cube002: Mesh
      Cube003: Mesh
      ['be_quiet!']: Mesh
      Cube017: Mesh
      BézierCurve: Mesh
      BézierCurve001: Mesh
      BézierCurve002: Mesh
      Baseboard: Mesh
      Curve: Mesh
      Curve001: Mesh
      Curve002: Mesh
      Curve003: Mesh
      Text: Mesh
      Cube005: Mesh
      Curve006: Mesh
      Curve004: Mesh
      Curve005: Mesh
      Curve007: Mesh
      Curve008: Mesh
      Curve009: Mesh
      Curve010: Mesh
      Curve011: Mesh
      Cube006: Mesh
      Curve015: Mesh
      Curve012: Mesh
      Curve013: Mesh
      Curve014: Mesh
      Curve016: Mesh
      Curve017: Mesh
      Cube007: Mesh
      Curve018: Mesh
      Curve019: Mesh
      Curve020: Mesh
      Text001: Mesh
      Cube008: Mesh
      Curve021: Mesh
      Cube014: Mesh
      Text002: Mesh
      Curve022: Mesh
      Cube015: Mesh
      Curve023: Mesh
      Text003: Mesh
      KeyboardButton021: Mesh
      Cube018: Mesh
      Cube019: Mesh
      kEYBOARDbASE: Mesh
      KeyboardButton: Mesh
      KeyboardButton001: Mesh
      KeyboardButton002: Mesh
      KeyboardButton003: Mesh
      KeyboardButton004: Mesh
      KeyboardButton005: Mesh
      KeyboardButton006: Mesh
      KeyboardButton007: Mesh
      KeyboardButton008: Mesh
      KeyboardButton009: Mesh
      KeyboardButton010: Mesh
      KeyboardButton011: Mesh
      KeyboardButton012: Mesh
      KeyboardButton013: Mesh
      KeyboardButton014: Mesh
      KeyboardButton015: Mesh
      KeyboardButton016: Mesh
      KeyboardButton018: Mesh
      KeyboardButton019: Mesh
      KeyboardButton020: Mesh
      KeyboardButtonSpace: Mesh
      KeyboardButtonSpace001: Mesh
      KeyboardButtonSpace002: Mesh
      KeyboardButtonSpace003: Mesh
      KeyboardButtonSpace004: Mesh
      KeyboardButtonSpace005: Mesh
      KeyboardButtonSpace006: Mesh
      KeyboardButtonSpace007: Mesh
      KeyboardButtonSpace008: Mesh
      Cylinder013: Mesh
      BézierCurve003: Mesh
      Plane009: Mesh
      Plane010: Mesh
      Plane011: Mesh
      Plane012: Mesh
      Plane013: Mesh
      Plane014: Mesh
      Plane015: Mesh
      Plane016: Mesh
      Plane017: Mesh
   }
   materials: {
      Walls: MeshStandardMaterial
      FloorBorder: MeshStandardMaterial
      Chair: MeshStandardMaterial
      ['Material.010']: MeshStandardMaterial
      ['Material.009']: MeshStandardMaterial
      ['Material.008']: MeshStandardMaterial
      ['Material.011']: MeshStandardMaterial
      ['Material.002']: MeshStandardMaterial
      ['Material.007']: MeshStandardMaterial
      Hexagon2: MeshStandardMaterial
      Hexagon3: MeshStandardMaterial
      ['Material.013']: MeshStandardMaterial
      Flower: MeshStandardMaterial
      Vaze: MeshStandardMaterial
      ['Material.005']: MeshStandardMaterial
      ['Material.004']: MeshStandardMaterial
      ['Material.003']: MeshStandardMaterial
      ['Material.006']: MeshStandardMaterial
      Flower1: MeshStandardMaterial
      BackgroundPlane: MeshStandardMaterial
      PictureFrame: MeshPhysicalMaterial
      CertReact: MeshStandardMaterial
      Cert: MeshStandardMaterial
      Cert1: MeshStandardMaterial
      ThomasText: MeshStandardMaterial
      Flooring: MeshStandardMaterial
      Shader: MeshStandardMaterial
      Blinder: MeshStandardMaterial
      ['Blinder.001']: MeshStandardMaterial
      WindowFrame: MeshStandardMaterial
      Window: MeshStandardMaterial
      WindowLight: MeshStandardMaterial
      Matress: MeshStandardMaterial
      Pillow: MeshStandardMaterial
      Pillow1: MeshStandardMaterial
      Sheet: MeshStandardMaterial
      BedFrame: MeshStandardMaterial
      DeskTable: MeshStandardMaterial
      DeskLeg1: MeshStandardMaterial
      ['Material.012']: MeshStandardMaterial
      DeskLeg: MeshStandardMaterial
      MonitorBase: MeshStandardMaterial
      ['Material.016']: MeshStandardMaterial
      MonitorScreen: MeshStandardMaterial
      PCCase: MeshStandardMaterial
      bequiet: MeshStandardMaterial
      KeyboardCable: MeshStandardMaterial
      Baseboard_material: MeshStandardMaterial
      ['SVGMat.001']: MeshStandardMaterial
      ['SVGMat.002']: MeshStandardMaterial
      Text: MeshStandardMaterial
      ['SVGMat.013']: MeshStandardMaterial
      ['SVGMat.010']: MeshStandardMaterial
      ['SVGMat.011']: MeshStandardMaterial
      ['SVGMat.012']: MeshStandardMaterial
      ['SVGMat.015']: MeshStandardMaterial
      ['SVGMat.016']: MeshStandardMaterial
      SVGMat: MeshStandardMaterial
      ['SVGMat.004']: MeshStandardMaterial
      ['SVGMat.005']: MeshStandardMaterial
      ['Material.014']: MeshStandardMaterial
      Keyboard: MeshStandardMaterial
      ['Material.001']: MeshStandardMaterial
      test: MeshStandardMaterial
   }
}

export default GLTFResult
